name: Deploy Chatbot

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t chatbot .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 chatbot
